CREATE TABLE `poke`.`poke` (
`pokedex_number` INT(3) UNSIGNED ZEROFILL NOT NULL,
`name` VARCHAR(45) NULL DEFAULT NULL,
`attack` VARCHAR(45) NULL DEFAULT NULL,
`classfication` VARCHAR(45) NULL DEFAULT NULL,
`defense` VARCHAR(45) NULL DEFAULT NULL,
`height_m` VARCHAR(45) NULL DEFAULT NULL,
`hp` VARCHAR(45) NULL DEFAULT NULL,
`speed` VARCHAR(45) NULL DEFAULT NULL,
`type1` VARCHAR(45) NULL DEFAULT NULL,
`type2` VARCHAR(45) NULL DEFAULT NULL,
`weight_kg` VARCHAR(45) NULL DEFAULT NULL,
`generation` VARCHAR(45) NULL DEFAULT NULL,
`is_legendary` VARCHAR(45) NULL DEFAULT NULL,
`abilities` VARCHAR(45) NULL DEFAULT NULL,
PRIMARY KEY (`pokedex_number`),
UNIQUE INDEX `pokedex_number_UNIQUE` (`pokedex_number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
